[profile.default]
src = 'invisible_solidity/src'
out = 'invisible_solidity/out'
libs = ['invisible_solidity/lib']
test = 'invisible_solidity/test'
via_ir = true



# See more config options https://github.com/foundry-rs/foundry/tree/master/config

